// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var PageComponent = {};

function $$default(props) {
  var content = React.createElement(props.Component, props.pageProps);
  return React.createElement("div", {
              className: "w-375 my-0 m-auto"
            }, content);
}

export {
  PageComponent ,
  $$default ,
  $$default as default,
}
/* react Not a pure module */
