// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var PageComponent = {};

function $$default(props) {
  var content = React.createElement(props.Component, props.pageProps);
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: "font-bold text-red-500"
                }, "런치런치"), React.createElement("div", {
                  className: "italic font-bold text-orange-300"
                }, content));
}

export {
  PageComponent ,
  $$default ,
  $$default as default,
}
/* react Not a pure module */
