// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Index$default(Props) {
  return React.createElement("div", {
              className: "border-1 border-black"
            }, "lunch roulette");
}

var $$default = Index$default;

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
