// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import $$Image from "next/image";
import LoadingBurgerPng from "../../public/loading-burger.png";

var burgerImage = LoadingBurgerPng;

var $$Image$1 = {};

function Loading$default(Props) {
  return React.createElement("div", {
              className: "w-100% h-screen flex flex-col items-center bg-gray2"
            }, React.createElement("h1", {
                  className: "loading-stroke pt-24 text-5xl text-primary whitespace-pre-wrap font-bold"
                }, "점심 메뉴\n찾는 중 ..."), React.createElement($$Image, {
                  alt: "loading...",
                  className: "pt-36",
                  height: 214,
                  src: burgerImage,
                  width: 214
                }));
}

var $$default = Loading$default;

export {
  burgerImage ,
  $$Image$1 as $$Image,
  $$default ,
  $$default as default,
}
/* burgerImage Not a pure module */
